### ISSUE TITLE
f-16 interface

### ISSUE THREAD

**Issue by vakosel** [Gadroc/helios#18]
Thanks for continuing this  useful project.
Are you planning to add interface for the f-16 c dcs  world? 
 
I hope you do !

**Comment by BlueFinBima** [comment]
Hello @vakosel,  This project is dormant (as far as I can tell).   There is an active fork here https://github.com/BlueFinBima/Helios .  There are plans to expand the number of interfaces, but nothing at the moment.
I would recommend closing this issue.  
Regards, BlueFinBima

**Comment by vakosel** [comment]
thanks
